#!/usr/bin/env python3
"""Gzips firmware/servo_controller/ui/index.html into index_html_gz.h.

Run this after editing the UI, then rebuild the firmware:
    python3 tools/build_ui.py
The generated header is committed so the sketch builds in the Arduino IDE without Python.
"""
import gzip
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "firmware/servo_controller/ui/index.html"
dst = root / "firmware/servo_controller/index_html_gz.h"

data = gzip.compress(src.read_bytes(), compresslevel=9, mtime=0)
rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
dst.write_text(
    "// Generated by tools/build_ui.py from ui/index.html. Do not edit by hand.\n"
    "#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n"
    "const uint8_t INDEX_HTML_GZ[] = {\n  " + ",\n  ".join(rows) + "\n};\n"
    "const size_t INDEX_HTML_GZ_LEN = sizeof(INDEX_HTML_GZ);\n"
)
print(f"{src.name}: {src.stat().st_size} bytes -> {len(data)} bytes gzipped -> {dst.relative_to(root)}")
